ifndef PETALINUX
$(error You must source the petalinux/settings.sh script before working with PetaLinux)
endif

# Point to default PetaLinux root directory
ifndef ROOTDIR
ROOTDIR=$(PETALINUX)/software/petalinux-dist
endif

PATH:=$(PATH):$(ROOTDIR)/tools

UCLINUX_BUILD_USER = 1
-include $(ROOTDIR)/.config
-include $(ROOTDIR)/$(CONFIG_LINUXDIR)/.config
LIBCDIR = $(CONFIG_LIBCDIR)
-include $(ROOTDIR)/config.arch
ROMFSDIR=$(ROOTDIR)/romfs
ROMFSINST=$(ROOTDIR)/tools/romfs-inst.sh

LDFLAGS+=-L../../common
LDLIBS+=-lpthread -lSDM

APPS = GetTimeTest

# Add any other object files to this list below
APP_OBJS = TatTask.o

all: $(APPS)

GetTimeTest: GetTimeTest.o
	$(CXX) $(LDFLAGS) -o $@ $^ $(LDLIBS)

clean:
	-rm -f $(APPS) *.elf *.gdb *.o

romfs:
	$(ROMFSINST) GetTimeTest /bin/GetTimeTest

%.o: %.cpp
	$(CXX) -c $(CXXFLAGS) -o $@ $<


# Targets for the required .config files - if they don't exist, the tree isn't
# configured.  Tell the user this, how to fix it, and exit.
${ROOTDIR}/config.arch ${ROOTDIR}/.config:
	@echo "Error: You must configure the PetaLinux tree before compiling your application"
	@echo ""
	@echo "Change directory to ../../petalinux-dist and 'make menuconfig' or 'make xconfig'"
	@echo ""
	@echo "Once the tree is configured, return to this directory, and re-run make."
	@echo ""
	@exit -1

