#ifndef __ASENSOR_H_
#define __ASENSOR_H_

#define		SENSOR_ANALOG_SOURCE	0x0001
#define 	SENSOR_THERMOCOUPLE	0x0002
#define		SENSOR_VGI_AMP		0x0003
#define		SENSOR_DIGITAL_IO	0x0004

#define		SENSOR_PRODUCT_ID	0xC001
#define		SENSOR_TIMEOUT_SEC	0xC002

#define		VGI_AMP_STAGE_TWO_GAIN	0x01
#define		VGI_AMP_STAGE_ONE_GAIN	0x02
#define		VGI_AMP_OFFSET		0x03

#define		ANALOG_SOURCE_DAC_OUT	0x01

#define		DIGITAL_IO_PROGRAM	0x01
#define		DIGITAL_IO_IO		0x02

#define		SENSOR_WRITE_FLASH	0xFA
#define		SENSOR_ERASE_FLASH	0xFB
#define		SENSOR_READB_FLASH	0xFC
#define		SENSOR_READW_FLASH	0xFD

#endif

